### ISSUE TITLE
Odd Bug Continually Lists Album as Updated 

### ISSUE THREAD

**Issue by DirtyOldMan66** [LusciousMedia/luscious#10]
https://members.luscious.net/c/superheroes/albums/sailor-jupiter-hentai-pics_98254/view/

The above album constantly appears to be updated according to the site, and it constantly stays at the top of my list of updated albums (even though no content is added or subtracted). To my knowledge, it hasn't been updated in months, yet it now appears to be updated almost every minute. Odd.

**Comment by KaySackey** [comment]
Anytime you load an album, it checks to make sure the # of pictures it found via the search engine is identical to the # of pictures that are actually in the main database. This album has one picture that's banned, so it continually sees that there's 173 pictures visible in search, instead of the 174 that it needs to find.

I've fixed the issue so it'll ignore banned pictures when its counting up images.
