### ISSUE TITLE
Video section is not working

### ISSUE THREAD

**Issue by Exiagan** [LusciousMedia/luscious#8]
My friend wanted to upload some videos to luscious. The video was broken or unplayable due to 404 or just basically download failure. Not just that, a few old videos around a week old have the same problem. So I can assume that this problem had been around for a week or so.

**Comment by Schwarzguy** [comment]
Exactly the same for me. I did upload a video after a many errors with non-permited uploads for a week or so. That bug (or wathever it was) just disappear magiclly.

Old videos of mine are also off and it happens with a lot of them in the site. At the beginning I thought that it was only with the old videos, like if was something related with an update. But then I started to search videos and it was randomly. Some are off, some are on. Really strange.

**Comment by KaySackey** [comment]
The uploading should be fixed as of now. This is the same issue as in #7.

**Comment by KaySackey** [comment]
One thing to note about videos is that on Chrome 53/54, videos occasionally fail if the browser tries to reload the mp4 before a particular chunk has finished loading.

There's no way for us to control this. Luckily its fixed in Chrome 57, so it should be a month or so before its fixed in the wild for everyone.
